public class XtraPensionConstants {
	public static final String FREEFORM_FIELD_DEFAULT_VALUE =
	    '<p>' +
		    '<strong>We believe that our client qualifies to pay Class 2 contributions under HMRC&#39;s stated criteria that: </strong>' +
  	    '</p>' +
  	    '<ul>' +
		    '<li>They were ordinarily employed (/self-employed) immediately before last leaving the UK (which includes unemployment where applicable)</li>' +
		    '<li>They are in employment which is not employment in respect of earnings from which Class 1 contributions are payable.</li>' +
		    '<li>They were and continue to be in employment abroad continuously paying social insurance (as verified by the official Govt contributions statement enclosed)</li>' +
		    '<li>They lived in the UK (/EU) for a continuous 3 year period before the period for which NI contributions are to be paid.</li>' +
		    '<li>They paid the qualifying amount of contributions in 3 years or more in UK (/EU)</li>' +
  	    '</ul>' +
  	    '<p>' +
		    'As our client was habitually resident in an EU country and was previously compulsorily insured in the UK, we believe they therefore qualify for voluntary Class 2 contributions under Article 14 of EC Regulation 883/2004 (and Article 32(1)(a) of the EU-UK Withdrawal Agreement Act 2020)' + 
  	    '</p>';
    public static final String FREEFORM_CLASS2_FIELD_DEFAULT_VALUE =
		'<p>We would appreciate it if you could ensure your assessment of their eligibility to pay Class 2 contributions, a statement of their National Insurance Contributions to date and the Class 2 Table of Voluntary National Insurance <b>SHORTFALL IS SENT DIRECTLY TO US</b> at "Suite 2/11, Pure Offices, 1 Ainslie Road, Hillington, Glasgow, G52 4RU" as the enclosed 64-8 authorises us to act as their agent. Our client\'s work history is below.</p>';
    public static final String  NINO_INFO =
        '<div class="message-item">' +
            '<b>&#8226; National Insurance Number</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/5ways" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/5ways</a>' +
        '</div>' +
        '<br/>';
    public static final String  LAST_UK_EMPLOYERS_INFO =
        '<div>' +
            '<b>&#8226; Last UK Work</b>' +
            '<br/> Company name, their old address, approx. work start & end dates (even if defunct)' +
        '</div>' +
        '<br/>';
    public static final String  PRSI_INFO =
        '<div class="message-item">' +
            '<b>&#8226; PRSI / Social Insurance Statement</b>' +
            '<br/>Watch this short explanation: ' +
            '<a href="https://xpen.uk/socins" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/socins</a>' +
        '</div>' +
        '<br/>';
    public static final String  WORK_AFTER_UK_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Work History</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/work" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/work</a>' +
        '</div>' +
        '<br/>';
    public static final String  C3_APPEAL_LETTER_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Rejection / CLASS 3 letter from HRMC</b>' +
            '<br/> Please send a full phone/scanned version to clients@xtrapension.com or WhatsApp' +
        '</div>' +
        '<br/>';
    public static final String  RELATIONSHIP_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Date of Marriage / Divorce / Bereavement</b>' +
            '<br/>When did this event happen?' +
        '</div>' +
        '<br/>';
    public static final String NINO_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Wrong NINO Provided by Our Client on CF83 Application</strong>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us that our client’s NINO as given does not match your records.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>They somehow had XXX different NINOs while in the UK but understood that the NINO they provided was the correct and final one.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed……</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and advise as to their National Insurance liability.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String CUSTOM_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Additional Information Requested by </strong>' +
            '<br/>' +
            '<strong style="font-size: 16px;">HMRC to Assess Our Client’s CF83 Application</strong>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>Thank you for your recent letter requesting more information on our client’s circumstances.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed……</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>The date they moved was …….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Their last UK Employer was …….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>They retired in ….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We understand this client is eligible for Class 2 voluntary NICs based on Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We understand this client is eligible for Class 2 voluntary NICs based on Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and calculate the correct NI liability for our client.</p>'   +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String APPEAL_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Appeal of Your Class 3 Approval Decision. Request for Class 2 Approval.</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us of HMRC’s acceptance of our client’s application to pay Class 3 voluntary NI contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We stated previously that our client wished to “pay Class 2 or Class 3  as applicable”, but also our understanding that they were eligible to pay Class 2 contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>Can you please explain your decision to NOT approve our client to pay Class 2 NI contributions or change your decision if applicable?</b></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Our client appears to clearly qualify to pay Class 2 contributions under HMRC’s stated criteria that:</p>' +
        '<ol>' +
            '<li>They were ordinarily employed (/self-employed) immediately before last leaving the UK (and unemployment is regarded as employment)</li>' +
            '<li>They have been and continue to be in employment abroad (Rep of Ireland) continuously paying social insurance (as verified by the official Irish Govt contributions statement enclosed again here)</li>' +
            '<li>They are in employment which is not employment in respect of earnings from which Class 1 contributions are payable.</li>' +
            '<li>They lived in the UK for a continuous three year period before the period for which NI contributions are to be paid (or EU equivalent)</li>' +
            '<li>They paid the qualifying amount of contributions in three years or more in UK (or EU)</li>' +
            '<li>We respectfully draw your attention to Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</li>' +
        '</ol>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String CURRENT_JOB_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Request for Continuation of Class 2 Status & Update of Your Records</strong>' +
            '<br/>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us of HMRC’s acceptance of our client’s application to pay Class 2 voluntary NI contributions up until {NINO}.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please note that our client’s recent employment did NOT in fact end on that date – this was simply the date of the CF83 application to you. We apologise for any confusion here.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>They remain employed abroad now</b> as per their recent formal payslip enclosed for verification.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and <b>confirm by return that they may continue to pay Class 2 voluntary NI contributions</b> until their employment circumstances change in the future.</p>' +
        '<p>' +
           '<br>' +
        '</p>' +
        '<p>Their current employment abroad is:</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Start Date:</p>' +
        '<p>Employer Name:</p>' +
        '<p>Employer Tel:</p>' +
        '<p>Employer Address:</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String DWP_STATUS_CHECK_TEMPLATE =
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>HMRC have advised in writing that they sent my application to pay voluntary NI contributions to you.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Can you please confirm you have received this and if not, request it from them?</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please then send NICs shortfall table and payment details ASAP to both myself and CC my HMRC-approved agent JGBA Ltd.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<p>My Email: {Customer Email}</p>' +
            '<p>Agent Email: nics@jgbaglasgow.co.uk</p>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
           'Yours sincerely' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '---------------------------------------' +
        '</p>' +
        '<p>' +
           '{FullName}' +
        '</p>';
    public static final String CERTIFIED_DOC_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Certified Copy of ID</strong>' +
            '<br/>' +
        '</h2>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find certified proof of my identity enclosed as requested.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Yours sincerely.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
           '<br>' +
        '</p>' +
        '<p>' +
            '---------------------------------------' +
        '</p>' +
        '<p>' +
            '{FullName}' +
        '</p>';
    public static final String EU_RESIDENCY_APPEAL_TEMPLATE =
        '<hr>' +
        '<h2>' +
            '<strong style="font-size: 14px;">FORMAL REQUEST FOR RECONSIDERATION</strong>' +
        '</h2>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We represent a large number of clients, both British and international, who have applied to make voluntary National Insurance contributions using the CF83 form.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We are writing to formally request a reconsideration of the recent decision regarding our client’s eligibility to pay voluntary contributions. While we appreciate the professionalism of your team, we believe the decision does not fully reflect HMRC’s own published guidance or the evidence previously submitted.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We address the key points of rejection below:</p>' +
        '<hr>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>1) Rejection based on ‘3-year criteria’ (Regulation 147(3)(a) and (b))</b></p>' +
        '<p>HMRC’s guidance NI38 states:<i>“If you lived or worked in an EU country, Iceland, Liechtenstein, Norway, Switzerland or Turkey, time spent there may help you to meet condition 2(a) or 2(b).”</i></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>The CF83 application guidance reinforces this, confirming that applicants <i>“may be able to pay voluntary Class 2 or voluntary Class 3 National Insurance contributions if you have… paid 3 years of social security contributions in an EU country, Gibraltar, Iceland, Liechtenstein, Norway, Switzerland, or Turkey.”</i></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Our client is an EU national with a clear history of employment and social insurance contributions within the EU. It is reasonable that they relied upon HMRC’s published guidance when applying. Our client reasonably expected that their EU social insurance contributions would be taken into account in satisfying the requirements of Regulation 147(3)(b). To interpret the legislation more narrowly than the published guidance indicates risks creating unfair outcomes.</p>' +
        '<hr>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>2) Rejection based on ‘No Evidence of Living in EU’</b></p>' +
        '<p>We have previously provided our client’s complete EU Social Insurance record, and we enclose it again with this letter. This record provides definitive evidence of both contributions and residency within the EU, before and after UK employment.</p>' +
        '<hr>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>3) Rejection based on ‘Brief History of Employment’</b></p>' +
        '<p>Regulation 147(1)(a) of The Social Security (Contributions) Regulations 2001 requires only that an individual be <i>“ordinarily an employed earner or ordinarily a self-employed earner”</i> immediately before leaving the UK. There is no reference to a minimum duration of employment.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Your own records confirm that our client was employed and paying National Insurance contributions in the UK immediately prior to departure. This meets the requirement set out in the legislation.</p>' +
        '<hr>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>Conclusion</b></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>In light of the above, we respectfully request that HMRC reconsider this application for voluntary Class 2 contributions, taking into account the clear guidance in NI38 and CF83, as well as the supporting evidence provided. We also request that a <b>Class 2 shortfall table</b> be issued to our client, setting out the eligible years and amounts payable.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We are happy to provide any further documentation required to assist in resolving this matter.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We look forward to your prompt reconsideration.</p>';
    public static final String MAIDEN_NAME =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Ref: Information Mismatching by HMRC on 64-8</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>We recently sent you a signed 64-8 along with a CF83 for our client and we note your response dated the 14th of January advising that you were unable to verify our client\'s details.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We stated previously that our client wished to “pay Class 2 or Class 3  as applicable”, but also our understanding that they were eligible to pay Class 2 contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please be advised that the 64-8 had the correct name of {Married_Name}. Their MAIDEN NAME which you likely have on your records is {Maiden_Name} and we have noted that while this appears on the CF83 there is no field for this information on the 64-8 form so may have been missed.</p>' +
        '<p>Our client got married on {Date_of_Marriage} and changed their name meaning the enclosed signed 64-8 is correct & accurate. </p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We trust that this will clarify the matter and we look forward to your earliest reply to their CF83 application.</p>';
    public static final String DWP_C2_REQUEST =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Request to Pay Class 2 NICs</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>I wish to pay Class 2 NICs for all the available past years that I was working abroad up until I reached UK State Pension Age</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed evidence of my post-UK work abroad as shown by social insurance/social security etc records.</p>' +
        '<br/>' +
        '<p><strong style="font-size: 16px;">Date I left the UK:{DateOfLeavingUK}</strong>.</p>' +
        'SPLIT=============' +
        '<p>I believe I qualify to pay Class 2 contributions for past years under HMRC\'s stated criteria that:</p>' +
        '<br/>' +
        '<ul>' +
        '<li>I was ordinarily employed (/self-employed) immediately before last leaving the UK</li>' +
        '<li>I was in employment which was not employment in respect of earnings from which Class 1 contributions were payable.</li>' +
        '<li>I was in employment abroad continuously paying social insurance (as verified by the official Govt contributions statement enclosed)</li>' +
        '<li>I lived in the UK (/EU) for a continuous 3 year period before the period for which NI contributions are to be paid.</li>' +
        '<li>I paid the qualifying amount of contributions in 3 years or more in UK (/EU)</li>' +
        '</ul>' +
        '<br/>' +
        '<p>As I was habitually resident in an EU country and was previously compulsorily insured in the UK, I believe I therefore qualify for voluntary Class 2 contributions under Article 14 of EC Regulation 883/2004, the shared ‘EU Residency’ rule.</p>' +
        '<br/>' +
        '<p>Yours sincerely</p>';
    public static final String BOUNCE_LETTER =
        '<p><b>Hi {First Name},</b></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We kindly ask that you review, sign, and post the enclosed letter to HMRC to ensure that your personal details on their records are accurate, particularly in light of any recent changes to your name, address, or other personal information.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Although we have already submitted your updated information to HMRC, they have advised us that your details <b><i>"do not match their records."</i></b> This may be the case even if everything appears to be correct on our end.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Unfortunately, we are unable to proceed with following up on your voluntary contributions application until HMRC has verified and updated your information. Having a signed letter directly from you will help expedite this process.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We apologise for any inconvenience and appreciate your cooperation.</p>';
    public static final String UPDATE_LETTER =
        '<p>Dear Sir/Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>You recently rejected the attached signed 64-8 authorisation form our agent sent to you. Can you please update and confirm by return that HMRC\'s records have now been updated with the following correct details:</p>';
    public static final String NOT_RECEIVED_CHECK_AGENT_MESSAGE = 'NOT RECEIVED by HMRC';
    public static final String C2_C3_CHECK_AGENT_MESSAGE = 'LETTER NOT RECEIVED by XP (Check with Client)';
    public static final String BAD_NINO_CHECK_AGENT_MESSAGE = 'BAD NINO after check';
    public static final String X64_8_CHECK_AGENT_MESSAGE = '64-8 ISSUE after check';
    public static final String REJECT_CHECK_AGENT_MESSAGE = 'REJECTION by HMRC (Check with Client)';
    public static final String APPEAL_CHECK_AGENT_MESSAGE = 'APPEAL NOT RECEIVED by HMRC';
}