public class XtraPensionConstants {
	public static final String FREEFORM_FIELD_DEFAULT_VALUE =
	    '<p>' +
		    '<strong>We believe that our client qualifies to pay Class 2 contributions under HMRC&#39;s stated criteria that: </strong>' +
  	    '</p>' +
  	    '<ul>' +
		    '<li>They were ordinarily employed (/self-employed) immediately before last leaving the UK (which includes unemployment where applicable)</li>' +
		    '<li>They are in employment which is not employment in respect of earnings from which Class 1 contributions are payable.</li>' +
		    '<li>They were and continue to be in employment abroad continuously paying social insurance (as verified by the official Govt contributions statement enclosed)</li>' +
		    '<li>They lived in the UK (/EU) for a continuous 3 year period before the period for which NI contributions are to be paid.</li>' +
		    '<li>They paid the qualifying amount of contributions in 3 years or more in UK (/EU)</li>' +
  	    '</ul>' +
  	    '<p>' +
		    'As our client was habitually resident in an EU country and was previously compulsorily insured in the UK, we believe they therefore qualify for voluntary Class 2 contributions under Article 14 of EC Regulation 883/2004 (and Article 32(1)(a) of the EU-UK Withdrawal Agreement Act 2020)' + 
  	    '</p>';
    public static final String FREEFORM_CLASS2_FIELD_DEFAULT_VALUE =
		'We would appreciate it if you could ensure your assessment of their eligibility to pay Class 2 contributions, a statement of their National Insurance Contributions to date and the Class 2 Table of Voluntary National Insurance <b>SHORTFALL IS SENT DIRECTLY TO US</b> at "Suite 2/11, Pure Offices, 1 Ainslie Road, Hillington, Glasgow, G52 4RU" as the enclosed 64-8 authorises us to act as their agent. Our client\'s work history is below.';
    public static final String  NINO_INFO =
        '<div class="message-item">' +
            '<b>&#8226; National Insurance Number</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/5ways" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/5ways</a>' +
        '</div>' +
        '<br/>';
    public static final String  LAST_UK_EMPLOYERS_INFO =
        '<div>' +
            '<b>&#8226; Last UK Work</b>' +
            '<br/> Company name, their old address, approx. work start & end dates (even if defunct)' +
        '</div>' +
        '<br/>';
    public static final String  PRSI_INFO =
        '<div class="message-item">' +
            '<b>&#8226; PRSI / Social Insurance Statement</b>' +
            '<br/>Watch this short explanation: ' +
            '<a href="https://xpen.uk/socins" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/socins</a>' +
        '</div>' +
        '<br/>';
    public static final String  WORK_AFTER_UK_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Work History</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/work" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/work</a>' +
        '</div>' +
        '<br/>';
    public static final String  RELATIONSHIP_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Date of Marriage / Divorce / Bereavement</b>' +
            '<br/>When did this event happen?' +
        '</div>' +
        '<br/>';
    public static final String NINO_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Wrong NINO Provided by Our Client on CF83 Application</strong>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us that our client’s NINO as given does not match your records.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>They somehow had XXX different NINOs while in the UK but understood that the NINO they provided was the correct and final one.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed……</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and advise as to their National Insurance liability.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String CUSTOM_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Additional Information Requested by </strong>' +
            '<br/>' +
            '<strong style="font-size: 16px;">HMRC to Assess Our Client’s CF83 Application</strong>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>Thank you for your recent letter requesting more information on our client’s circumstances.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed……</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>The date they moved was …….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Their last UK Employer was …….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>They retired in ….</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We understand this client is eligible for Class 2 voluntary NICs based on Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We understand this client is eligible for Class 2 voluntary NICs based on Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and calculate the correct NI liability for our client.</p>'   +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String APPEAL_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Appeal of Your Class 3 Approval Decision. Request for Class 2 Approval.</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us of HMRC’s acceptance of our client’s application to pay Class 3 voluntary NI contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We stated previously that our client wished to “pay Class 2 or Class 3  as applicable”, but also our understanding that they were eligible to pay Class 2 contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>Can you please explain your decision to NOT approve our client to pay Class 2 NI contributions or change your decision if applicable?</b></p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Our client appears to clearly qualify to pay Class 2 contributions under HMRC’s stated criteria that:</p>' +
        '<ol>' +
            '<li>They were ordinarily employed (/self-employed) immediately before last leaving the UK (and unemployment is regarded as employment)</li>' +
            '<li>They have been and continue to be in employment abroad (Rep of Ireland) continuously paying social insurance (as verified by the official Irish Govt contributions statement enclosed again here)</li>' +
            '<li>They are in employment which is not employment in respect of earnings from which Class 1 contributions are payable.</li>' +
            '<li>They lived in the UK for a continuous three year period before the period for which NI contributions are to be paid (or EU equivalent)</li>' +
            '<li>They paid the qualifying amount of contributions in three years or more in UK (or EU)</li>' +
            '<li>We respectfully draw your attention to Article 14 of EC directive 883/2004 confirmed by Article 32(1)(a) of the EU-UK Withdrawal Agreement 2020.</li>' +
        '</ol>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String CURRENT_JOB_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Request for Continuation of Class 2 Status & Update of Your Records</strong>' +
            '<br/>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you for your recent letter advising us of HMRC’s acceptance of our client’s application to pay Class 2 voluntary NI contributions up until {NINO}.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please note that our client’s recent employment did NOT in fact end on that date – this was simply the date of the CF83 application to you. We apologise for any confusion here.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><b>They remain employed abroad now</b> as per their recent formal payslip enclosed for verification.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We would be grateful if you could update your records accordingly and <b>confirm by return that they may continue to pay Class 2 voluntary NI contributions</b> until their employment circumstances change in the future.</p>' +
        '<p>' +
           '<br>' +
        '</p>' +
        '<p>Their current employment abroad is:</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Start Date:</p>' +
        '<p>Employer Name:</p>' +
        '<p>Employer Tel:</p>' +
        '<p>Employer Address:</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Thank you in advance and we look forward to a positive reply at your earliest convenience.</p>';
    public static final String DWP_STATUS_CHECK_TEMPLATE =
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>HMRC have advised in writing that they sent my application to pay voluntary NI contributions to you.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Can you please confirm you have received this and if not, request it from them?</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please then send NICs shortfall table and payment details ASAP to both myself and CC my HMRC-approved agent JGBA Ltd.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<p>My Email: {Customer Email}</p>' +
            '<p>Agent Email: nics@jgbaglasgow.co.uk</p>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
           'Yours sincerely' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '---------------------------------------' +
        '</p>' +
        '<p>' +
           '{FullName}' +
        '</p>';
    public static final String CERTIFIED_DOC_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Certified Copy of ID</strong>' +
            '<br/>' +
        '</h2>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find certified proof of my identity enclosed as requested.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Yours sincerely.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>' +
           '<br>' +
        '</p>' +
        '<p>' +
            '---------------------------------------' +
        '</p>' +
        '<p>' +
            '{FullName}' +
        '</p>';
    public static final String EU_RESIDENCY_APPEAL_TEMPLATE =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Appeal Against HMRC Refusal to Approve Class 2 NICs </strong>' +
            '<br/>' +
        '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>Thank you for your recent letter advising that our client is NOT eligible to pay Class 2 voluntary NI contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>*** Your reply appears to be an outdated template from the time of HMRC\'s guidance error between 17 November 2017 and 8 April 2019. As per NI38 2025 guidance, you seem to have omitted the critical word \'OR\'.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>====</p>' +
        '<p>From HMRC NI38 Guidance Notes: "You can pay Class 2 National Insurance contributions if....</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>1 - Immediately before going abroad, you were ordinarily an employed or self-employed earner in the UK (= YES)</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>2 - You ALSO satisfy EITHER of the following conditions:</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>A - You’ve lived in the UK for a continuous 3 year period (= YES as per EEA RESIDENCY AGGREGATION via EC Article 14)</p>' +
        '<p> \'OR\'</p>' + 
        '<p>B - You paid 3 years National Insurance (= NO)</p>' +
        '<p>====</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We provided proof (enclosed now again) of our client\'s EEA residence from the time they left the UK - therefore they clearly qualify for Class 2 NICs under the RESIDENCY condition starting with their time in the UK.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>As per HMRC internal guidance note NIM71150, Article 14 of EC Regulation 883/2004 ensures the aggregation of social security periods and prevents gaps in eligibility, enabling our client to qualify for voluntary Class 2 NICs with less than 3 years of UK work/residency as per the criteria you have detailed which we note are from Section 147 of The Social Security (Contributions) Regulations 2001.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Even though HMRC normally requires 3 years of work or residence to qualify for voluntary Class 2 NICs, Article 14 allows people to count the time they were insured or working in another EEA country toward those 3 years. </p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>(The Brexit Withdrawal Agreement & EU/UK Trade and Cooperation Agreement from Dec 31 2020 also facilitates this aggregation of social security periods in most cases)</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please clarify if our understanding here is wrong or revise your decision if appropriate.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Only in the case that our client is still NOT entitled to Class 2 for their eligible working years abroad as we believe they clearly are, would they then like to formally apply via this letter to pay Class 3 NICs given that all necessary information has been provided to you in the CF83 previously submitted.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We look forward to receiving your decision and a correct NICs shortfall table soonest.</p>';
    public static final String MAIDEN_NAME =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Ref: Information Mismatching by HMRC on 64-8</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>We recently sent you a signed 64-8 along with a CF83 for our client and we note your response dated the 14th of January advising that you were unable to verify our client\'s details.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We stated previously that our client wished to “pay Class 2 or Class 3  as applicable”, but also our understanding that they were eligible to pay Class 2 contributions.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please be advised that the 64-8 had the correct name of {Married_Name}. Their MAIDEN NAME which you likely have on your records is {Maiden_Name} and we have noted that while this appears on the CF83 there is no field for this information on the 64-8 form so may have been missed.</p>' +
        '<p>Our client got married on {Date_of_Marriage} and changed their name meaning the enclosed signed 64-8 is correct & accurate. </p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>We trust that this will clarify the matter and we look forward to your earliest reply to their CF83 application.</p>';
    public static final String DWP_C2_REQUEST =
        '<h2 style="text-align: center;">' +
            '<strong style="font-size: 16px;">Request to Pay Class 2 NICs</strong>' +
            '<br/>' +
            '</h2>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Dear Sir / Madam</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>I wish to pay Class 2 NICs for all the available past years that I was working abroad up until I reached UK State Pension Age</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p>Please find enclosed evidence of my post-UK work abroad as shown by social insurance/social security etc records.</p>' +
        '<p>' +
            '<br>' +
        '</p>' +
        '<p><strong style="font-size: 16px;">Date I left the UK:{DateOfLeavingUK}</strong>.</p>';
}