public class XtraPensionConstatns {
	public static final String FREEFORM_FIELD_DEFAULT_VALUE =
	    '<p>' +
		    '<strong>We believe that our client qualifies to pay Class 2 contributions under HMRC&#39;s stated criteria that: </strong>' +
  	    '</p>' +
  	    '<ul>' +
		    '<li>They were ordinarily employed (/self-employed) immediately before last leaving the UK (which includes unemployment where applicable)</li>' +
		    '<li>They are in employment which is not employment in respect of earnings from which Class 1 contributions are payable.</li>' +
		    '<li>They were and continue to be in employment abroad continuously paying social insurance (as verified by the the official Govt contributions statement enclosed)</li>' +
		    '<li>They lived in the UK (/EU) for a continuous 3 year period before the period for which NI contributions are to be paid.</li>' +
		    '<li>They paid the qualifying amount of contributions in 3 years or more in UK (/EU)</li>' +
  	    '</ul>' +
  	    '<p>' +
		    'As our client was habitually resident in an EU country and was previously compulsorily insured in the UK, we believe they therefore qualify for voluntary Class 2 contributions under Article 14 of EC Regulation 883/2004 (and Article 32(1)(a) of the EU-UK Withdrawal Agreement Act 2020)' + 
  	    '</p>';
    public static final String FREEFORM_CLASS2_FIELD_DEFAULT_VALUE =
		'<div>We would appreciate it if you could ensure your assessment of their eligibility to pay Class 2 contributions, a statement of their National Insurance Contributions to date and the Class 2 Table of Voluntary National Insurance <b>SHORTFALL IS SENT DIRECTLY TO US</b> at "Suite 2/11, Pure Offices, 1 Ainslie Road, Hillington, Glasgow, G52 4RU" as the enclosed 64-8 authorises us to act as their agent. Our client\'s work history is below.</div>';
    public static final String  NINO_INFO =
        '<div class="message-item">' +
            '<b>&#8226; National Insurance Number</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/5ways" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/5ways</a>' +
        '</div>' +
        '<br/>';
    public static final String  LAST_UK_EMPLOYERS_INFO =
        '<div>' +
            '<b>&#8226; Last UK Work</b>' +
            '<br/> Company name, their old address, approx. work start & end dates (even if defunct)' +
        '</div>' +
        '<br/>';
    public static final String  PRSI_INFO =
        '<div class="message-item">' +
            '<b>&#8226; PRSI / Social Insurance Statement</b>' +
            '<br/>Watch this short explanation: ' +
            '<a href="https://xpen.uk/socins" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/socins</a>' +
        '</div>' +
        '<br/>';
    public static final String  WORK_AFTER_UK_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Work History</b>' +
            '<br/> Watch this short explanation: ' +
            '<a href="https://xpen.uk/work" style="color: #1aa2b0; text-decoration: underline">https://xpen.uk/work</a>' +
        '</div>' +
        '<br/>';
    public static final String  RELATIONSHIP_INFO =
        '<div class="message-item">' +
            '<b>&#8226; Date of Marriage / Divorce / Bereavement</b>' +
            '<br/>When did this event happen?' +
        '</div>' +
        '<br/>';
}